### PR TITLE
readability changes for stringRotation

### PR DESCRIPTION
**Pull request by jackskennel**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I believe the first loop is unnecessary because we assign the shifted values into the output array in the 2nd loop.

**Comment by jackskennel** [comment]
> 
> 
> I believe the first loop is unnecessary because we assign the shifted values into the output array in the 2nd loop. Also, we can merge line 16 and 17 together to yield return new String(output).

see second commit. the two lines are merged already

**Comment by ghost** [comment]
Yep, I edited my comment.

**Comment by jackskennel** [comment]
> 
> 
> I believe the first loop is unnecessary because we assign the shifted values into the output array in the 2nd loop.

updated accordingly.

**Comment by ghost** [comment]
> > I believe the first loop is unnecessary because we assign the shifted values into the output array in the 2nd loop.
> 
> updated accordingly.

Great!

**Review by ben44496 — APPROVED** [review]
Looks good. Might want to add some comments but that's not too important. If it's an issue, someone can submit an issue for it and then I'll change it.

**Pull request merged**
